# $PANDAS$

In [72]:
import pandas as pd
import numpy as np

In [2]:
orders = pd.read_excel("order_raw.xlsx")
customers = pd.read_excel("customers_raw.xlsx",)
products = pd.read_excel("products_raw.xlsx")

In [3]:
orders.set_index("order id", inplace = True)
orders.head()

,order date,variant sku,product qty,subtotal price,discount,Tax,total price,customer id
order id,,,,,,,,
100,2025-11-01 01:45:23,HERB127,3.0,1350.0,27.00,67.5,1390.50,85
101,2025-11-01 02:19:55,HERB174,2.0,624.0,12.48,31.2,642.72,488
102,2025-11-01 02:54:27,HERB002,2.0,360.0,7.20,18.0,370.80,111
103,2025-11-01 03:28:59,HERB130,4.0,720.0,14.40,36.0,741.60,507
104,2025-11-01 04:03:31,HERB010,3.0,642.0,12.84,32.1,661.26,1080

In [4]:
customers.set_index("Customer ID", inplace = True)
customers.head()

,First Name,Last Name,FullName,Phone Number,Email ID,City,State,Country,Postal Code
Customer ID,,,,,,,,,
1,Aarav,Seshad,Aarav Seshad,6.068536e+08,AaravSeshad60@gmail.com,Pune,Maharashtra,India,51522.0
2,Abhay,Sodhi,Abhay Sodhi,2.779010e+09,AbhaySodhi27@gmail.com,Chandigarh,Chandigarh,India,143410.0
3,Amogh,Shankar,Amogh Shankar,9.117981e+11,AmoghShankar91@gmail.com,Hyderabad,Telangana,India,95396.0
4,Armaan,Viswanathan,Armaan Viswanathan,1.888881e+09,ArmaanViswanathan18@gmail.com,Shimla,Himachal Pradesh,India,540515.0
5,Balaji,Natarajan,Balaji Natarajan,9.105853e+11,BalajiNatarajan91@gmail.com,Vadodara,Gujarat,India,43030.0

In [5]:
products.set_index("Variant SKU", inplace= True)
products.head()

,Variant Price,Cost per item,Variant Inventory Qty,True SKU margins,Product Name,Category
Variant SKU,,,,,,
HERB001,250,160.0,120,90.0,Amla Hair Oil,Hair care
HERB002,180,110.0,200,70.0,Neem Face Wash,Skin care
HERB003,300,190.0,150,110.0,Tulsi Green Tea,Teas
HERB004,90,50.0,300,40.0,Aloe Vera Gel,Skin care
HERB005,220,140.0,180,80.0,Ashwagandha Capsules,capsules/Tablets

In [6]:
orders.info(), products.info(), customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14596 entries, 100 to 14695
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order date      14596 non-null  datetime64[ns]
 1   variant sku     14596 non-null  object
 2   product qty     14580 non-null  float64
 3   subtotal price  14589 non-null  float64
 4   discount        14581 non-null  float64
 5   Tax             14579 non-null  float64
 6   total price     14586 non-null  float64
 7   customer id     14596 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 1.0+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 176 entries, HERB001 to HERB176
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Variant Price          176 non-null    int64
 1   Cost per item          176 non-null    float64
 2   Variant Inventory Qty  176 non-null    int64
 3   True SKU margins       176 non-null    float64
 4   Product Name           176 non-null    object
 5   Category               176 non-null    object
dtypes: float64(2), int64(2), object(2)
memory usage: 9.6+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 1 to 1200
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   First Name    1200 non-null   object
 1   Last Name     1194 non-null   object
 2   FullName      1200 non-null   object
 3   Phone Number  1180 non-null   float64
 4   Email ID      1182 non-null   object
 5   City          1200 non-null   object
 6   State         1183 non-null   object
 7   Country       1200 non-null   object
 8   Postal Code   1169 non-null   float64
dtypes: float64(2), object(7)
memory usage: 93.8+ KB

(None, None, None)

In [7]:
orders.describe()

,order date,product qty,subtotal price,discount,Tax,total price,customer id
count,14596,14580.000000,14589.000000,14581.000000,14579.000000,14586.000000,14596.000000
mean,2026-04-25 01:52:23.002172416,2.498491,840.871341,16.818368,42.029563,866.341220,598.754179
min,2025-11-01 01:45:23,1.000000,80.000000,1.600000,4.000000,82.400000,1.000000
25%,2026-01-27 13:48:53.000999936,2.000000,429.000000,8.580000,21.450000,441.870000,299.000000
50%,2026-04-25 01:52:23.001999872,2.000000,752.000000,15.040000,37.600000,774.560000,602.000000
75%,2026-07-21 13:55:53.003000064,4.000000,1156.000000,23.120000,57.800000,1192.225000,894.000000
max,2026-10-17 01:59:23.004000,4.000000,2156.000000,43.120000,107.800000,2220.680000,1200.000000
std,NaN,1.115123,492.260558,9.846469,24.608573,506.959693,345.519152

In [8]:
products.describe()

       Variant Price  Cost per item  Variant Inventory Qty  True SKU margins
count     176.000000     176.000000             176.000000        176.000000
mean      336.318182     268.031818             480.022727         68.286364
std       114.209786      92.571812             212.469775         22.701558
min        80.000000      50.000000             120.000000         16.000000
25%       237.250000     183.200000             318.000000         48.650000
50%       341.500000     273.200000             426.500000         69.200000
75%       424.500000     339.600000             645.500000         86.100000
max       539.000000     431.200000             979.000000        110.000000

In [9]:
orders.shape, products.shape, customers.shape

((14596, 8), (176, 6), (1200, 9))

In [10]:
orders.columns

Index(['order date', 'variant sku', 'product qty', 'subtotal price',
       'discount', 'Tax', 'total price', 'customer id'],
      dtype='object')

In [11]:
products.columns

Index(['Variant Price', 'Cost per item', 'Variant Inventory Qty',
       'True SKU margins', 'Product Name', 'Category'],
      dtype='object')

In [12]:
customers.columns

Index(['First Name', 'Last Name', 'FullName', 'Phone Number', 'Email ID',
       'City', 'State', 'Country', 'Postal Code'],
      dtype='object')

In [13]:
orders.dtypes

order date        datetime64[ns]
variant sku               object
product qty              float64
subtotal price           float64
discount                 float64
Tax                      float64
total price              float64
customer id                int64
dtype: object

In [14]:
products["Product Name"] #1-D

Variant SKU
HERB001                      Amla Hair Oil
HERB002                     Neem Face Wash
HERB003                    Tulsi Green Tea
HERB004                      Aloe Vera Gel
HERB005               Ashwagandha Capsules
                        ...
HERB172                 Giloy Herbal Juice
HERB173    Turmeric Skin Brightening Cream
HERB174             Sandalwood Herbal Soap
HERB175                Hibiscus Herbal Tea
HERB176               Arjuna Herbal Powder
Name: Product Name, Length: 176, dtype: object

In [15]:
products[["Product Name", "Category"]] #2-D

                                Product Name          Category
Variant SKU
HERB001                        Amla Hair Oil         Hair care
HERB002                       Neem Face Wash         Skin care
HERB003                      Tulsi Green Tea              Teas
HERB004                        Aloe Vera Gel         Skin care
HERB005                 Ashwagandha Capsules  capsules/Tablets
...                                      ...               ...
HERB172                   Giloy Herbal Juice      Herbal juice
HERB173      Turmeric Skin Brightening Cream         Skin care
HERB174               Sandalwood Herbal Soap         Skin care
HERB175                  Hibiscus Herbal Tea              Teas
HERB176                 Arjuna Herbal Powder     Herbal powder

[176 rows x 2 columns]

In [16]:
customers.loc[[67], ["FullName"]] #Customer ID

               FullName
Customer ID
67           Trisha Sha

In [17]:
customers.iloc[[66], [2]] #Index

               FullName
Customer ID
67           Trisha Sha

In [18]:
customers.at[67, 'FullName']

'Trisha Sha'

In [19]:
customers.iat[67,2]

'Urvashi Oza'

In [20]:
orders.query("`customer id`>100 and Tax>105") #filter rows

,order date,variant sku,product qty,subtotal price,discount,Tax,total price,customer id
order id,,,,,,,,
264,2025-11-05 00:08:51.000,HERB129,4.0,2156.0,43.12,107.8,2220.68,648
273,2025-11-05 05:19:39.000,HERB075,4.0,2116.0,42.32,105.8,2179.48,761
314,2025-11-06 04:55:31.000,HERB160,4.0,2108.0,42.16,105.4,2171.24,565
387,2025-11-07 22:56:27.000,HERB160,4.0,2108.0,42.16,105.4,2171.24,742
521,2025-11-11 04:03:55.000,HERB160,4.0,2108.0,42.16,105.4,2171.24,271
...,...,...,...,...,...,...,...,...
14257,2026-10-06 13:53:47.004,HERB153,4.0,2128.0,42.56,106.4,2191.84,194
14320,2026-10-08 02:09:23.004,HERB075,4.0,2116.0,42.32,105.8,2179.48,215
14390,2026-10-09 18:26:43.004,HERB160,4.0,2108.0,42.16,105.4,2171.24,327
14450,2026-10-11 04:58:43.004,HERB152,4.0,2152.0,43.04,107.6,2216.56,326
14624,2026-10-15 09:07:31.004,HERB153,4.0,2128.0,42.56,106.4,2191.84,1162

In [21]:
orders[(orders["Tax"]>105) & (orders["customer id"]>100)] #Boolean indexing

,order date,variant sku,product qty,subtotal price,discount,Tax,total price,customer id
order id,,,,,,,,
264,2025-11-05 00:08:51.000,HERB129,4.0,2156.0,43.12,107.8,2220.68,648
273,2025-11-05 05:19:39.000,HERB075,4.0,2116.0,42.32,105.8,2179.48,761
314,2025-11-06 04:55:31.000,HERB160,4.0,2108.0,42.16,105.4,2171.24,565
387,2025-11-07 22:56:27.000,HERB160,4.0,2108.0,42.16,105.4,2171.24,742
521,2025-11-11 04:03:55.000,HERB160,4.0,2108.0,42.16,105.4,2171.24,271
...,...,...,...,...,...,...,...,...
14257,2026-10-06 13:53:47.004,HERB153,4.0,2128.0,42.56,106.4,2191.84,194
14320,2026-10-08 02:09:23.004,HERB075,4.0,2116.0,42.32,105.8,2179.48,215
14390,2026-10-09 18:26:43.004,HERB160,4.0,2108.0,42.16,105.4,2171.24,327
14450,2026-10-11 04:58:43.004,HERB152,4.0,2152.0,43.04,107.6,2216.56,326
14624,2026-10-15 09:07:31.004,HERB153,4.0,2128.0,42.56,106.4,2191.84,1162

In [22]:
orders.isna().sum()

order date         0
variant sku        0
product qty       16
subtotal price     7
discount          15
Tax               17
total price       10
customer id        0
dtype: int64

In [23]:
orders[orders["total price"].isna()]

,order date,variant sku,product qty,subtotal price,discount,Tax,total price,customer id
order id,,,,,,,,
342,2025-11-06 21:02:27,HERB011,1.0,80.0,1.60,4.0,NaN,215
343,2025-11-06 21:36:59,HERB035,3.0,630.0,12.60,31.5,NaN,1112
344,2025-11-06 22:11:31,HERB088,3.0,648.0,12.96,32.4,NaN,759
345,2025-11-06 22:46:03,HERB127,3.0,1350.0,27.00,67.5,NaN,860
346,2025-11-06 23:20:35,HERB051,2.0,402.0,8.04,20.1,NaN,777
347,2025-11-06 23:55:07,HERB024,1.0,110.0,2.20,5.5,NaN,5
348,2025-11-07 00:29:39,HERB175,1.0,432.0,8.64,21.6,NaN,756
349,2025-11-07 01:04:11,HERB009,4.0,416.0,8.32,20.8,NaN,676
350,2025-11-07 01:38:43,HERB088,1.0,216.0,4.32,10.8,NaN,652
351,2025-11-07 02:13:15,HERB130,1.0,180.0,3.60,9.0,NaN,26

In [24]:
tot = orders["subtotal price"] - orders["discount"] + orders["Tax"]
orders["total price"] = orders["total price"].fillna(tot)
orders["total price"].isna().sum()

np.int64(0)

In [25]:
sub = orders["total price"] + orders["discount"] - orders["Tax"]
orders["subtotal price"] = orders["subtotal price"].fillna(sub)

In [26]:
dis = orders["subtotal price"] + orders["Tax"] - orders["total price"]
orders["discount"] = orders["discount"].fillna(dis)

In [27]:
tax = orders["total price"] - orders["subtotal price"] + orders["discount"]
orders["Tax"] = orders["Tax"].fillna(tax)

In [29]:
orders.loc[[342,343]]

,order date,variant sku,product qty,subtotal price,discount,Tax,total price,customer id
order id,,,,,,,,
342,2025-11-06 21:02:27,HERB011,1.0,80.0,1.6,4.0,82.4,215
343,2025-11-06 21:36:59,HERB035,3.0,630.0,12.6,31.5,648.9,1112

In [37]:
products["variant sku"] = products.index

In [40]:
orders = orders.merge(
    products[["variant sku", "Variant Price"]],
    on="variant sku",
    how="left"
)

In [41]:
orders.head()

,order date,variant sku,product qty,subtotal price,discount,Tax,total price,customer id,Variant Price
0,2025-11-01 01:45:23,HERB127,3.0,1350.0,27.00,67.5,1390.50,85,450
1,2025-11-01 02:19:55,HERB174,2.0,624.0,12.48,31.2,642.72,488,312
2,2025-11-01 02:54:27,HERB002,2.0,360.0,7.20,18.0,370.80,111,180
3,2025-11-01 03:28:59,HERB130,4.0,720.0,14.40,36.0,741.60,507,180
4,2025-11-01 04:03:31,HERB010,3.0,642.0,12.84,32.1,661.26,1080,214

In [42]:
qty = orders["subtotal price"] // orders["Variant Price"]
orders["product qty"] = orders["product qty"].fillna(qty)

In [43]:
orders.isna().sum()

order date        0
variant sku       0
product qty       0
subtotal price    0
discount          0
Tax               0
total price       0
customer id       0
Variant Price     0
dtype: int64

In [44]:
products.isna().sum()

Variant Price            0
Cost per item            0
Variant Inventory Qty    0
True SKU margins         0
Product Name             0
Category                 0
variant sku              0
dtype: int64

In [46]:
customers.isna().sum()

First Name       0
Last Name        6
FullName         0
Phone Number    20
Email ID        18
City             0
State           17
Country          0
Postal Code     31
dtype: int64

In [50]:
customers[customers["Last Name"].isna()]

,First Name,Last Name,FullName,Phone Number,Email ID,City,State,Country,Postal Code
Customer ID,,,,,,,,,
121,Nishita,NaN,Nishita Balakrishnan,2.771670e+09,NishitaBalakrishnan27@gmail.com,Hyderabad,NaN,India,899358.0
122,Paridhi,NaN,Paridhi Kothari,5.628900e+09,ParidhiKothari56@gmail.com,Bengaluru,NaN,India,217535.0
123,Pratima,NaN,Pratima Tripathi,9.186632e+11,PratimaTripathi91@gmail.com,Shimla,NaN,India,751701.0
124,Ragini,NaN,Ragini Banik,8.019949e+09,RaginiBanik80@gmail.com,Gurgaon,NaN,India,503758.0
147,Balram,NaN,Balram Gandhi,9.118432e+11,NaN,Noida,Uttar Pradesh,India,651777.0
163,Shashwat,NaN,Shashwat Anand,9.136916e+11,ShashwatAnand91@gmail.com,Dehradun,NaN,India,347955.0

In [51]:
sur = customers["FullName"].str.split().str[-1]
customers["Last Name"] = customers["Last Name"].fillna(sur)

In [52]:
customers.loc[[121,122]]

,First Name,Last Name,FullName,Phone Number,Email ID,City,State,Country,Postal Code
Customer ID,,,,,,,,,
121,Nishita,Balakrishnan,Nishita Balakrishnan,2.771670e+09,NishitaBalakrishnan27@gmail.com,Hyderabad,NaN,India,899358.0
122,Paridhi,Kothari,Paridhi Kothari,5.628900e+09,ParidhiKothari56@gmail.com,Bengaluru,NaN,India,217535.0

In [53]:
customers["Phone Number"] = customers["Phone Number"].fillna("Unknown")

In [55]:
customers["State"] = customers["State"].fillna(customers.groupby("City")["State"].transform("first"))

In [57]:
customers["Postal Code"].fillna(0, inplace=True)
customers["Email ID"].fillna("Unknown", inplace=True)

In [58]:
customers.isna().sum()

First Name      0
Last Name       0
FullName        0
Phone Number    0
Email ID        0
City            0
State           0
Country         0
Postal Code     0
dtype: int64

In [59]:
customers["Postal Code"].astype(int)

Customer ID
1        51522
2       143410
3        95396
4       540515
5        43030
         ...
1196    959953
1197    568566
1198    882634
1199    398373
1200    678544
Name: Postal Code, Length: 1200, dtype: int64

In [60]:
products.head()

,Variant Price,Cost per item,Variant Inventory Qty,True SKU margins,Product Name,Category,variant sku
Variant SKU,,,,,,,
HERB001,250,160.0,120,90.0,Amla Hair Oil,Hair care,HERB001
HERB002,180,110.0,200,70.0,Neem Face Wash,Skin care,HERB002
HERB003,300,190.0,150,110.0,Tulsi Green Tea,Teas,HERB003
HERB004,90,50.0,300,40.0,Aloe Vera Gel,Skin care,HERB004
HERB005,220,140.0,180,80.0,Ashwagandha Capsules,capsules/Tablets,HERB005

In [66]:
products["ishighmargin"] = products["True SKU margins"].apply(lambda x : 1 if x>80 else 0) #slow

In [67]:
products.head()

,Variant Price,Cost per item,Variant Inventory Qty,True SKU margins,Product Name,Category,variant sku,ishighmargin
Variant SKU,,,,,,,,
HERB001,250,160.0,120,90.0,Amla Hair Oil,Hair care,HERB001,1
HERB002,180,110.0,200,70.0,Neem Face Wash,Skin care,HERB002,0
HERB003,300,190.0,150,110.0,Tulsi Green Tea,Teas,HERB003,1
HERB004,90,50.0,300,40.0,Aloe Vera Gel,Skin care,HERB004,0
HERB005,220,140.0,180,80.0,Ashwagandha Capsules,capsules/Tablets,HERB005,0

In [70]:
products["needrefill"] = (products["Variant Inventory Qty"]<150).astype(int) #fastest

In [73]:
products["isexpensive"] = np.where(products["Variant Price"] >200, 1, 0)

In [74]:
products.head()

,Variant Price,Cost per item,Variant Inventory Qty,True SKU margins,Product Name,Category,variant sku,ishighmargin,needrefill,isexpensive
Variant SKU,,,,,,,,,,
HERB001,250,160.0,120,90.0,Amla Hair Oil,Hair care,HERB001,1,1,1
HERB002,180,110.0,200,70.0,Neem Face Wash,Skin care,HERB002,0,0,0
HERB003,300,190.0,150,110.0,Tulsi Green Tea,Teas,HERB003,1,0,1
HERB004,90,50.0,300,40.0,Aloe Vera Gel,Skin care,HERB004,0,0,0
HERB005,220,140.0,180,80.0,Ashwagandha Capsules,capsules/Tablets,HERB005,0,0,1